---
# Global variables for AAP configuration

# SSL verification setting for AAP connections
apd_verify_ssl: false

# Controller connection settings
controller_hostname: "{{ groups.automationcontroller[0] | default(ansible_fqdn) | default(ansible_hostname) | default('aap.demo.local') }}"
controller_username: admin

# Try to get password from various sources that the AAP installer might set
controller_password: "{{ controller_admin_password | default(gateway_admin_password) | default(hub_admin_password) | default(new_install_password) | default(lookup('env', 'AAP_ADMIN_PASSWORD')) | default('admin') }}"

controller_validate_certs: "{{ apd_verify_ssl }}"

# Set a consistent admin password variable for other uses
aap_admin_password: "{{ controller_password }}"