---
- name: Configure Ansible Automation Platform Post-Install
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - group_vars/all.yml
  tasks:

    - name: Wait for Controller to be ready before configuration
      ansible.builtin.uri:
        url: "https://{{ groups.automationcontroller[0] | default('aap.demo.local') }}/api/v2/ping/"
        method: GET
        validate_certs: "{{ apd_verify_ssl }}"
        status_code: 200
        timeout: 30
      register: controller_ping
      until: controller_ping.status == 200
      retries: 30
      delay: 10

    - name: Wait additional time for Controller services to fully initialize
      ansible.builtin.pause:
        seconds: 30

    - name: Configure Controller Credential Types
      ansible.builtin.include_role:
        name: infra.controller_configuration.credential_types
      vars:
        controller_credential_types: "{{ lookup('file', 'aap-configs/controller_credential_types.yaml') | from_yaml }}"

    - name: Configure Controller Credentials
      ansible.builtin.include_role:
        name: infra.controller_configuration.credentials
      vars:
        controller_credentials: "{{ lookup('file', 'aap-configs/controller_credentials.yaml') | from_yaml }}"

    - name: Configure Controller Projects
      ansible.builtin.include_role:
        name: infra.controller_configuration.projects
      vars:
        controller_projects: "{{ lookup('file', 'aap-configs/controller_projects.yaml') | from_yaml }}"
      when: lookup('file', 'aap-configs/controller_projects.yaml', errors='ignore') != ''

    - name: Configure Controller Job Templates
      ansible.builtin.include_role:
        name: infra.controller_configuration.job_templates
      vars:
        controller_job_templates: "{{ lookup('file', 'aap-configs/controller_job_templates.yaml') | from_yaml }}"
      when: lookup('file', 'aap-configs/controller_job_templates.yaml', errors='ignore') != ''

    - name: Configure Controller Workflow Job Templates
      ansible.builtin.include_role:
        name: infra.controller_configuration.workflow_job_templates
      vars:
        controller_workflow_job_templates: "{{ lookup('file', 'aap-configs/controller_workflow_job_templates.yaml') | from_yaml }}"
      when: lookup('file', 'aap-configs/controller_workflow_job_templates.yaml', errors='ignore') != ''
