---
# AAP Controller Configuration as Code
# This file should contain configuration variables as a dictionary/hash

# Controller connection settings - use variables that should be available from AAP installer
controller_hostname: "{{ ansible_fqdn | default(ansible_hostname) | default('aap.demo.local') }}"
controller_username: admin
controller_password: "{{ controller_admin_password | default(gateway_admin_password) | default(hub_admin_password) }}"
controller_validate_certs: false

# Import credential types configuration
controller_credential_types: "{{ (lookup('file', 'aap-configs/controller_credential_types.yaml', errors='ignore') | from_yaml).controller_credential_types | default([]) }}"

# Import credentials configuration
controller_credentials: "{{ (lookup('file', 'aap-configs/controller_credentials.yaml', errors='ignore') | from_yaml).controller_credentials | default([]) }}"

# Import projects configuration
controller_projects: "{{ (lookup('file', 'aap-configs/controller_projects.yaml', errors='ignore') | from_yaml).controller_projects | default([]) }}"

# Import job templates configuration
controller_job_templates: "{{ (lookup('file', 'aap-configs/controller_job_templates.yaml', errors='ignore') | from_yaml).controller_job_templates | default([]) }}"

# Import workflow job templates configuration
controller_workflow_job_templates: "{{ (lookup('file', 'aap-configs/controller_workflow_job_templates.yaml', errors='ignore') | from_yaml).controller_workflow_job_templates | default([]) }}"

# Import organizations configuration
controller_organizations: "{{ (lookup('file', 'aap-configs/controller_organizations.yaml', errors='ignore') | from_yaml).controller_organizations | default([]) }}"

# Import teams configuration
controller_teams: "{{ (lookup('file', 'aap-configs/controller_teams.yaml', errors='ignore') | from_yaml).controller_teams | default([]) }}"

# Import users configuration
controller_users: "{{ (lookup('file', 'aap-configs/controller_users.yaml', errors='ignore') | from_yaml).controller_users | default([]) }}"

# Import inventories configuration
controller_inventories: "{{ (lookup('file', 'aap-configs/controller_inventories.yaml', errors='ignore') | from_yaml).controller_inventories | default([]) }}"

# Import schedules configuration
controller_schedules: "{{ (lookup('file', 'aap-configs/controller_schedules.yaml', errors='ignore') | from_yaml).controller_schedules | default([]) }}"