---
controller_settings:
  - settings:
      ACTIVITY_STREAM_ENABLED: "true"
      ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: "false"
      ORG_ADMINS_CAN_SEE_ALL_USERS: "true"
      MANAGE_ORGANIZATION_AUTH: "true"
      TOWER_URL_BASE: "https://aap.simon-lynch.sbx.hashidemos.io:8443"
      PROXY_IP_ALLOWED_LIST:
        []
      CSRF_TRUSTED_ORIGINS:
        []
      LICENSE:
        sku: MW02049
        trial: false
        usage: ''
        pool_id: 2c949aaf9299c8100192b6c941db6864
        satellite: false
        valid_key: true
        license_date: '1761105599'
        license_type: enterprise
        product_name: Red Hat Partner Subscription (500 Nodes)
        support_level: Self-Support
        account_number: '11525892'
        instance_count: 1000
        subscription_id: '15712247'
        subscription_name: Red Hat Partner Subscription (500 Nodes)
      REDHAT_USERNAME: ""
      REDHAT_PASSWORD: ""
      SUBSCRIPTIONS_CLIENT_ID: ""
      SUBSCRIPTIONS_CLIENT_SECRET: ""
      INSTALL_UUID: "65d7d5da-5289-4c47-adbc-f4d0d9f22e72"
      DEFAULT_EXECUTION_ENVIRONMENT: "null"
      CUSTOM_VENV_PATHS:
        []
      INSIGHTS_TRACKING_STATE: "false"
      AUTOMATION_ANALYTICS_LAST_ENTRIES: ""
      AUTOMATION_ANALYTICS_GATHER_INTERVAL: "14400"
      CLEANUP_HOST_METRICS_LAST_TS: "2025-06-11T07:36:27.089811Z"
      HOST_METRIC_SUMMARY_TASK_LAST_TS: "2025-06-18T12:06:28.111548Z"
...
