---
eda_decision_environments:
  - name: "Default Decision Environment"
    description: ""
    image_url: "registry.redhat.io/ansible-automation-platform-25/de-supported-rhel8:latest"
    organization: "Default"
    eda_credential: "Decision Environment Container Registry"
  - name: "Hub Default Decision Environment"
    description: ""
    image_url: "aap.demo.local/de-supported-rhel8:latest"
    organization: "Default"
    eda_credential: "Hub Decision Environment Container Registry"
...
