---
gateway_routes:
  - name: "hub container registry"
    description: !unsafe 'Hub Container Registry.'
    http_port: "1"
    service_cluster: "3"
    service_port: "8444"
    is_service_https: "True"
    service_path: "/v2/"
    gateway_path: "/v2/"
    enable_gateway_auth: "True"
    node_tags: ""
  - name: "hub ui"
    description: !unsafe 'Hub UI'
    http_port: "1"
    service_cluster: "3"
    service_port: "8444"
    is_service_https: "True"
    service_path: "/ui/"
    gateway_path: "/ui/"
    enable_gateway_auth: "True"
    node_tags: ""
  - name: "hub ui static files"
    description: !unsafe 'Hub UI Static Files'
    http_port: "1"
    service_cluster: "3"
    service_port: "8444"
    is_service_https: "True"
    service_path: "/static/galaxy_ng/"
    gateway_path: "/static/galaxy_ng/"
    enable_gateway_auth: "True"
    node_tags: ""
  - name: "pulp content"
    description: !unsafe 'Pulp Content'
    http_port: "1"
    service_cluster: "3"
    service_port: "8444"
    is_service_https: "True"
    service_path: "/pulp"
    gateway_path: "/pulp"
    enable_gateway_auth: "True"
    node_tags: ""
  - name: "pulp container tokens"
    description: !unsafe 'Pulp Container Tokens'
    http_port: "1"
    service_cluster: "3"
    service_port: "8444"
    is_service_https: "True"
    service_path: "/token"
    gateway_path: "/token"
    enable_gateway_auth: "True"
    node_tags: ""
  - name: "pulp container extensions"
    description: !unsafe 'Pulp Container Extensions'
    http_port: "1"
    service_cluster: "3"
    service_port: "8444"
    is_service_https: "True"
    service_path: "/extensions"
    gateway_path: "/extensions"
    enable_gateway_auth: "True"
    node_tags: ""
  - name: "Event Driven Automation Event Stream"
    description: !unsafe 'Proxy to the EDA Event Streams'
    http_port: "1"
    service_cluster: "4"
    service_port: "8445"
    is_service_https: "True"
    service_path: "/"
    gateway_path: "/eda-event-streams/"
    enable_gateway_auth: "False"
    node_tags: "eda-event-stream,eda-hybrid"
...
